# Generated by Django 2.1.1 on 2018-10-14 14:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('adress', models.CharField(max_length=50)),
                ('prize', models.IntegerField()),
                ('deposit', models.BooleanField()),
                ('description', models.TextField(max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='media')),
                ('status', models.CharField(blank=True, choices=[('a', 'available'), ('u', 'unavailable')], default='m', max_length=1)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.City')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=30, null=True)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('date_of_rent', models.DateField(blank=True, null=True)),
                ('date_of_surrender', models.DateField(blank=True, null=True)),
                ('flat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.Flat')),
            ],
            options={
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
