# Generated by Django 2.1.1 on 2018-09-04 20:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Flats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unikatowy klucz id', primary_key=True, serialize=False)),
                ('adres', models.CharField(max_length=50)),
                ('cena', models.IntegerField()),
                ('kaucja', models.BooleanField()),
                ('opis', models.TextField(max_length=500)),
                ('status', models.CharField(blank=True, choices=[('d', 'Dostępne'), ('n', 'Niedostępne')], default='m', help_text='Dostępność mieszkania', max_length=1)),
                ('miasto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.Cities')),
            ],
        ),
    ]
