# Generated by Django 2.1.1 on 2018-09-05 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='wojewodztwo',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
