# Generated by Django 2.1.1 on 2018-09-05 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_cities_wojewodztwo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cities',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='flats',
            options={'verbose_name_plural': 'Flats'},
        ),
    ]
