# Generated by Django 2.1.1 on 2018-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_auto_20180905_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='flats',
            name='data_oddania',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flats',
            name='data_wynajecia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
