# Generated by Django 2.1.1 on 2018-09-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20180905_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='data_oddania',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flats',
            name='data_wynajecia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
