# Generated by Django 2.1.1 on 2018-09-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0005_auto_20180905_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='wojewodztwo',
        ),
    ]
