# Generated by Django 2.1.1 on 2018-10-03 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_auto_20181003_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservations',
            options={'verbose_name_plural': 'Reservations'},
        ),
        migrations.RemoveField(
            model_name='flats',
            name='data_oddania',
        ),
        migrations.RemoveField(
            model_name='flats',
            name='data_wynajecia',
        ),
    ]
