# Generated by Django 2.1.1 on 2018-10-03 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0009_remove_flats_rezerwacje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservations',
            name='mieszkanie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rentals.Flats'),
        ),
    ]
