# Generated by Django 2.1.1 on 2018-10-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0010_auto_20181003_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='telefon',
            field=models.CharField(help_text='Telefon kontaktowy', max_length=15, null=True),
        ),
    ]
