# Generated by Django 2.1.1 on 2018-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0011_reservations_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flats',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
