# Generated by Django 2.1.1 on 2018-10-08 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0012_auto_20181003_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='nazwisko',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
